### ISSUE TITLE
密码允许输入大于20个字符。应该添加一个提示或者限制输入。

### ISSUE THREAD

**Issue by hanwnz** [Nextmeta/PersonalOnlineMall#8]
或者你想截断这个字符?
我感觉应该加一个条件:
在登录源码的124行
`me.loginPwdVal.length < 6 || me.loginPwdVal.length > 20`

**Comment by GCYCLJKHG** [comment]
@hanwnz 这只是  最初的版本   先写出来一个大概的样式   然后再具体优化
